language: node_js
sudo: false
node_js:
    - '4'
    - '5'
install:
    - npm install
    - npm run typings
before_script: 
    - npm run lint
script:
    - npm run tsc
    - npm run build
cache:
  directories:
    - node_modules
webhooks:
   urls:
     - https://webhooks.gitter.im/e/32700b5e86c53be6204e
   on_success: change  # options: [always|never|change] default: always
   on_failure: always  # options: [always|never|change] default: always
   on_start: never
